// <auto-generated />
using Desfran.Models.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Desfran.Migrations
{
    [DbContext(typeof(DesfranContext))]
    [Migration("20220821071826_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("Desfran.Models.Entities.Account", b =>
                {
                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Email");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Email = "Admin@gmail.com",
                            Id = 1,
                            Password = "1621568719813777238110130818113881921121202386373191",
                            Username = "Admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
